name: nodeseek鸡腿签到

on:
  push:
    branches:
      - main
  schedule:
    - cron: '00 16 * * *'  # 北京时间 00:00 (UTC+8)
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  run-nodeseek-sign:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码仓库
        uses: actions/checkout@v3

      - name: 配置Python环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.8'

      - name: 安装依赖包
        run: |
          pip install curl_cffi requests

      - name: 运行签到脚本
        env:
          # 基本账号，从 Secrets 调用
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}

          # Cookie，从 Secrets 调用
          NS_COOKIE: ${{ secrets.NS_COOKIE }}

          # Telegram 推送配置
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          TG_THREAD_ID: ${{ secrets.TG_THREAD_ID }}

          # GitHub 自动刷新 Cookie（可选）
          GH_PAT: ${{ secrets.GH_PAT }}

          # 验证码服务（如果需要）
          SOLVER_TYPE: ${{ secrets.SOLVER_TYPE }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          CLIENTT_KEY: ${{ secrets.CLIENTT_KEY }}

        run: python nodeseek_sign.py
