name: nodeseek鸡腿签到

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 16 * * *'  # UTC 16:00 = 北京时间 00:00
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  run-nodeseek-sign:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码仓库
        uses: actions/checkout@v3

      - name: 配置Python环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.8'

      - name: 安装依赖包
        run: |
          pip install curl_cffi requests

      - name: 随机延迟执行
        run: |
          delay=$((RANDOM % 32400))   # 随机等待 0~32400 秒 (0~9 小时)
          echo "随机延迟 $delay 秒 (~$((delay/3600)) 小时 $(( (delay%3600) / 60 )) 分) 后开始签到..."
          sleep $delay

      - name: 运行签到脚本
        env:
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}
          NS_COOKIE: ${{ secrets.NS_COOKIE }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          TG_THREAD_ID: ${{ secrets.TG_THREAD_ID }}
          GH_PAT: ${{ secrets.GH_PAT }}
          SOLVER_TYPE: ${{ secrets.SOLVER_TYPE }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          CLIENTT_KEY: ${{ secrets.CLIENTT_KEY }}
        run: python nodeseek_sign.py
